development:
  adapter: postgresql
  encoding: unicode
  database: yelp_development
  pool: 5
#  username: YOUR_USERNAME
  #password: YOUR_PASSWORD

test:
  adapter: postgresql
  encoding: unicode
  database: yelp_test
  pool: 5
#  username: YOUR_USERNAME
  #password: YOUR_PASSWORD
